name: GitHub Self-Hosted Runner Monitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  runner-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # -----------------------------
      # Step 1: Fetch ORG-level runners
      # -----------------------------

      - name: Get org runners
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.ORG_RUNNER_TOKEN }}" \
            https://api.github.com/orgs/skc949/actions/runners \
            | jq '.runners // []'

      
      - name: Get repos and their runners
        run: |
          REPOS=$(curl -s -H "Authorization: Bearer ${{ secrets.ORG_RUNNER_TOKEN }}" \
            https://api.github.com/orgs/skc949/repos | jq -r '.[]?.name')
          for repo in $REPOS; do
            echo "Checking $repo"
            curl -s -H "Authorization: Bearer ${{ secrets.ORG_RUNNER_TOKEN }}" \
              https://api.github.com/repos/Sk81345/$repo/actions/runners \
              | jq '.runners // []'
          done
